version: '3'

services:
  #MySQL Service
  database:
    image: mysql:latest
    container_name: database
    command: --default-authentication-plugin=mysql_native_password
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce-api
    ports:
      - '3306:3306'
    networks:
      - app-network
    volumes:
      - ./database:/var/lib/mysql

  #PHP Service
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: application
    tty: true
    environment:
      SERVICE_NAME: application
      SERVICE_TAGS:
    working_dir: /var/www/html
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/html
    networks:
      - app-network
    links:
      - database

  #Nginx Service
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '8080:80'
    volumes:
      - ./public:/var/www/html/public
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    networks:
      - app-network
    links:
      - database
      - php

  #RabbitMQ Service
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/log/:/var/log/rabbitmq/
    networks:
      - app-network
    links:
      - database
      - php
      - nginx

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
